#MANAGE SKIM REFERENCES
#Author: Alex Bell, Renaissance Planning
#Last updated: Oct. 2018
"""
This is the geoprocessing interface for creating, storing, and modifying
skim reference configuration files for use in MMA analyses.

Skim reference config files define how to create a `mma.Skim` object, 
detailing the key fields in a skim table and how to parse them when 
running an accessibility analysis.  Skim reference config files are
required to run the `summarizeAccessibility` geoprocessing tool.

Batches of skim reference config files may be created by running this tool,
but all `skim tables` must have identical structures.  For multiple tables
with variable structure, the tool must be run multiple times.

Skim tables : [ArcGIS Table or Table View,...]
	A list of skim tables for which skim reference config files will be
	created.  All tables in the list must have identical structures.
Impedance field : Field
	The field in each `skim table` containing the operative	cumulative 
	impedance (usually travel time) value for calculating accessibility.
Skim uses single OD field : Boolean, optional
	If checked (True), the `skim tables` have origin-destination ID's 
	organized in a single field. Skim tables produced by the 
	`gp_createSkims` geoprocessor, for example, include a "Name" field 
	which containts both origin and destination ID values, separated by 
	the character string " - ".  If unchecked (False), the `skim tables`
	have separate columns for origin and destination ID's.
Origin field : Field
	If `skim uses single OD field` is false, the field in each `skim 
	table` that identifies the origin zone associated with each record.
	If `skim uses single OD field` is true, this is the name of the field
	containing combined origin and destination ID values.
Destination field : Field, optional
	If `skim uses single OD field` is false, the field in each `skim 
	table` that identifies the destination zone associated with each 
	record. If `skim uses single OD field` is true, this parameter is
	ignored.
Delimiter value : String, optional
	If `skim uses single OD field` is true, the character string used to
	appropriately parse origin and destination IDs from the combined
	values stored in `origin field`. If `skim uses single OD field` is 
	false, this parameter is ignored.
Output folder : Folder
	The folder where all skim reference config files generated by the
	tool will be stored.  A skim reference config file (.json) will be
	created for each table listed in `skim tables`.  Each output skim 
	reference config file takes its name from the corresponding 
	`skim table` it describes and includes an absolute path reference
	to that `skim table`.

See Also
---------
mma.Skim
mma.jsonToSkim
mma.skimToJson
gp_summarizeAccessibility
"""

import arcpy
import mma


if __name__ == "__main__":    
    skim_tables = arcpy.GetParameterAsText(0) # table view, multivalue
    impedance_field = arcpy.GetParameterAsText(1) # string, field from first skim table
    single_od_field = arcpy.GetParameter(2) # boolean
    o_field = arcpy.GetParameterAsText(3) # string, field from first skim table
    d_field = arcpy.GetParameterAsText(4) # string, field from first skim table, optional
    delimiter = arcpy.GetParameterAsText(5) # string, optional
    output_folder = arcpy.GetParameterAsText(6) #folder

    skim_tables = skim_tables.split(';')

    for skim_table in skim_tables:
        skim_table = arcpy.Describe(skim_table).catalogPath
        path, table = skim_table.rsplit('\\', 1)
        skim = mma.Skim(path, table, impedance_field, o_field,
                        d_field=d_field, delimiter=delimiter)
        skim_file = mma._getSkimFileName(output_folder, table)
        mma.skimToJson(skim, skim_file)
        
